import { defineConfig } from 'vite';
import { resolve } from 'path';
import { POSTS } from './src/data/posts.js';

// blog/<slug>/index.html files are generated by scripts/generate-blog-posts.mjs
// (run via the predev/prebuild npm hooks) before Vite reads this config.
const blogEntries = Object.fromEntries(
  POSTS.map((post) => [`blog-${post.slug}`, resolve(__dirname, `blog/${post.slug}/index.html`)])
);

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        product: resolve(__dirname, 'product.html'),
        shop: resolve(__dirname, 'shop.html'),
        story: resolve(__dirname, 'story.html'),
        contact: resolve(__dirname, 'contact.html'),
        ingredients: resolve(__dirname, 'ingredients.html'),
        blog: resolve(__dirname, 'blog.html'),
        post: resolve(__dirname, 'post.html'),
        bestkids: resolve(__dirname, 'best-kids-hydration-drink.html'),
        ...blogEntries,
      },
    },
  },
});
