// Shared product-detail-page rendering, used by both the legacy
// product.html (?flavor= query param) and the static /products/<slug>/
// pages generated by scripts/generate-product-pages.mjs.
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { FLAVORS } from '../../data/products.js';
import { cart } from '../../lib/cart.js';
import { hydrateProducts } from '../../lib/shopify.js';

gsap.registerPlugin(ScrollTrigger);

// Bundle-specific copy/images that don't live in src/data/products.js —
// each bundle's PDP presentation differs enough (tagline, hero art, price
// unit) that a flat override table is clearer than branching everywhere.
const BUNDLE_OVERRIDES = {
  'variety-pack': {
    name: 'Wild Variety Bundle',
    tagline: 'All 4 flavors. All 4 critters. One box of each.',
    creatureTag: 'The whole wild crew',
    color: '#4ADB14',
    colorDark: '#0b5f8a',
    creatureImg: '/assets/img/creature-kraken.png',
    packImg: '/assets/img/wild-family.png',
    priceUnit: '/ 4 boxes · 32 stick packs',
    actionImg: '/assets/img/action-bundle.png',
    pourImg: '/assets/img/pour-bundle.png',
    insideCopy: '4 boxes × 8 stick packs = 32 total hydration sticks — one box of each flavor, so every kid in the house gets their favorite critter. Zero sugar, zero artificial dyes, zero junk.',
    galleryImgs: [
      '/assets/img/wild-family.png',
      '/assets/img/facts-bundle.png',
      '/assets/img/comparison-chart.png',
      '/assets/img/nutrient-focused.png',
      '/assets/img/suggested-use.png',
    ],
  },
  'starter-kit': {
    name: 'Wild Starter Kit',
    tagline: 'The perfect intro to HydroWild.',
    creatureTag: 'Try every flavor',
    color: '#4ADB14',
    colorDark: '#0b5f8a',
    creatureImg: '/assets/img/creature-kraken.png',
    packImg: '/assets/img/starter-kit-sunglasses.jpg',
    priceUnit: '/ starter kit',
    actionImg: '/assets/img/starter-kit-sunglasses.jpg',
    pourImg: '/assets/img/starter-kit-sunglasses.jpg',
    insideCopy: 'A taste of every flavor in one box — so your family can find their favorite critter before going all-in. Zero sugar, zero artificial dyes, zero junk.',
    galleryImgs: [
      '/assets/img/starter-kit-sunglasses.jpg',
      '/assets/img/facts-bundle.png',
      '/assets/img/comparison-chart.png',
      '/assets/img/nutrient-focused.png',
      '/assets/img/suggested-use.png',
    ],
  },
};

/** Build the unified "product" object the rest of the page renders from. */
export function resolveProduct({ bundle, flavor }) {
  if (bundle) {
    return { ...bundle, ...BUNDLE_OVERRIDES[bundle.id] };
  }
  return {
    ...flavor,
    creatureTag: flavor.presents,
    priceUnit: '/ box · 8 stick packs',
    actionImg: `/assets/img/action-${flavor.id}.png`,
    pourImg: `/assets/img/pour-${flavor.id}.png`,
  };
}

const WILD_DIFF = [
  {
    t: 'Real Fruit Flavor',
    b: 'Crafted with real fruit-inspired flavor for a taste kids love — and parents approve. No artificial junk, just pure hydration fun.',
  },
  {
    t: '9 Essential Vitamins & Electrolytes',
    b: 'Every stick packs 9 vitamins (A, B6, B9, B12, C, D & K) and electrolytes, including potassium and magnesium, to help fuel active kids all day long.',
  },
  {
    t: 'Clean Label Promise',
    b: 'No artificial dyes, no artificial flavors, no fillers. Just ingredients you can actually pronounce — and feel good handing to your kid.',
  },
  {
    t: 'Zero Sugar, Naturally Sweet',
    b: 'Sweetened the smart way, with zero grams of sugar and no artificial sweeteners. Hydration kids ask for, without the sugar crash.',
  },
];

const REVIEWS = [
  {
    q: 'My little loves the taste and begs to have one every day. When friends come over they want them too.',
    n: 'Chase M.',
  },
  {
    q: 'My daughter LOVES these! Such an easy, delicious way to keep your kiddos hydrated — and perfect for our Disney bag!',
    n: 'Leslie G.',
  },
  {
    q: "A must-have for busy sports fams! My kids love this — it's their go-to for sports. Love having these packets on the go!",
    n: '@ThePerfectHouseWife',
  },
];

/**
 * Render the full interactive PDP into the current document.
 * `product` comes from resolveProduct(); `bundle`/`flavor` are whichever
 * one resolveProduct was called with (exactly one is set).
 */
export function renderPDP(product, { bundle, flavor, cartUI }) {
  document.title = `HydroWild ${product.name} — Kids Daily Hydration`;
  const pdp = document.getElementById('pdp');
  pdp.style.setProperty('--pdp-glow', `${product.color}4d`);
  pdp.style.setProperty('--pdp-accent', product.color);

  document.getElementById('creatureTag').textContent = product.creatureTag;
  document.getElementById('title').textContent = product.name;
  document.getElementById('title').style.color = product.color;
  document.getElementById('tagline').textContent = product.tagline;
  document.getElementById('price').textContent = `$${product.price.toFixed(2)}`;
  document.getElementById('creatureBg').src = product.creatureImg;
  const priceUnitEl = document.getElementById('priceUnit');
  if (priceUnitEl) priceUnitEl.textContent = product.priceUnit;

  // Bundle-specific "what's inside" copy
  if (bundle) {
    const inside = document.getElementById('accInside');
    if (inside) inside.textContent = BUNDLE_OVERRIDES[bundle.id].insideCopy;
  }

  // ── Hydrate price from Shopify (no-op in mock mode) ──
  hydrateProducts([product.handle]).then((priceMap) => {
    const data = priceMap.get(product.handle);
    if (!data) return;
    product.price = data.price; // keep in-memory for cart
    if (bundle) bundle.price = data.price;
    if (flavor) flavor.price = data.price;
    document.getElementById('price').textContent = `$${data.price.toFixed(2)}`;
  });

  // ── Gallery — pack shot + supplement facts, science, comparison chart &
  //    how-to-use as scrollable images (CJ request 2026-07-19) ──
  const galleryImgs = bundle
    ? BUNDLE_OVERRIDES[bundle.id].galleryImgs
    : [
        product.packImg,
        `/assets/img/facts-${product.id}.png`,
        `/assets/img/science-${product.id}.png`,
        '/assets/img/comparison-chart.png',
        '/assets/img/suggested-use.png',
        product.creatureImg,
      ];
  const mainImg = document.getElementById('mainImg');
  const thumbs = document.getElementById('thumbs');
  mainImg.src = galleryImgs[0];
  mainImg.alt = `HydroWild ${product.name}`;

  galleryImgs.forEach((src, i) => {
    const btn = document.createElement('button');
    btn.className = i === 0 ? 'active' : '';
    btn.innerHTML = `<img src="${src}" alt="View ${i + 1}" loading="lazy" />`;
    btn.addEventListener('click', () => {
      thumbs.querySelectorAll('button').forEach((b) => b.classList.remove('active'));
      btn.classList.add('active');
      gsap.fromTo(mainImg, { opacity: 0, scale: 0.92 }, { opacity: 1, scale: 1, duration: 0.4 });
      mainImg.src = src;
    });
    thumbs.appendChild(btn);
  });

  // ── Quantity + add to cart ──
  let qty = 1;
  const qtyVal = document.getElementById('qtyVal');
  document.getElementById('qtyInc').addEventListener('click', () => { qty = Math.min(qty + 1, 10); qtyVal.textContent = qty; });
  document.getElementById('qtyDec').addEventListener('click', () => { qty = Math.max(qty - 1, 1); qtyVal.textContent = qty; });
  document.getElementById('addBtn').addEventListener('click', () => {
    if (bundle) {
      cart.add({ ...bundle, packImg: bundle.img }, qty);
      cartUI?.toast(`${qty}× ${bundle.name} added!`);
    } else {
      cart.add(flavor, qty);
      cartUI?.toast(`${qty}× ${flavor.name} added — ${flavor.creature} approves.`);
    }
    cartUI?.open();
  });

  // ── The Wild Difference (copy mirrors hydrowild.com PDP) ──
  const diffAcc = document.getElementById('diffAcc');
  if (diffAcc) {
    diffAcc.innerHTML = WILD_DIFF.map(
      (d, i) => `
      <div class="pdp__acc-item${i === 2 ? ' open' : ''}">
        <button class="pdp__acc-head">${d.t} <span>+</span></button>
        <div class="pdp__acc-body"><div class="pdp__acc-body-inner">${d.b}</div></div>
      </div>`
    ).join('');
  }
  const diffImg = document.getElementById('diffImg');
  if (diffImg) { diffImg.src = product.actionImg; diffImg.alt = `HydroWild ${product.name} in action`; }

  // ── Testimonial band — flavor-dark background ──
  const quoteBand = document.getElementById('quoteBand');
  if (quoteBand) quoteBand.style.background = product.colorDark || '#0b5f8a';
  const quoteImg = document.getElementById('quoteImg');
  if (quoteImg) { quoteImg.src = product.pourImg; quoteImg.alt = `HydroWild ${product.name} being poured`; }

  // ── Why parents love HydroWild — real customer quotes ──
  const whyGrid = document.getElementById('whyGrid');
  if (whyGrid) {
    whyGrid.innerHTML = REVIEWS.map(
      (r) => `
      <div class="pdp-why__card" style="--why-color:${product.color}">
        <span class="pdp-why__stars">★★★★★</span>
        <p class="pdp-why__quote">&ldquo;${r.q}&rdquo;</p>
        <p class="pdp-why__name">${r.n}</p>
        <p class="pdp-why__verified">Verified Customer</p>
      </div>`
    ).join('');
  }

  // ── Common questions from parents (copy mirrors hydrowild.com PDP) ──
  const colorSource = product.id === 'blue-raspberry' ? 'spirulina extract (color)' : 'fruit & vegetable juice powder (color)';
  const flavorLine = bundle ? "each flavor's natural fruit flavor" : `natural ${product.name.toLowerCase()} flavor`;
  const FAQS = [
    ['Does it contain any common allergens?', "HydroWild is free from the most common allergens — no gluten, no dairy, no nuts, no soy. It's also vegan-friendly. As always, if your child has specific sensitivities, we recommend reviewing the full ingredient list."],
    ['What ages can drink HydroWild?', "HydroWild is formulated for children ages 4 and up, through teens. It's designed to meet the nutritional needs of active, growing kids — not toddlers, not adults. If your child is under 4 or has specific health conditions, check with your pediatrician first."],
    ["If there's no sugar, then how does it taste so sweet?", "Great question — and one we get a lot! HydroWild is sweetened with stevia (Reb A), a plant-based sweetener that gives it that naturally sweet taste without any sugar or artificial sweeteners. It's the same clean-label sweetener used in premium adult wellness products, just formulated to taste great for kids."],
    ['Is it better than sports drinks?', "Most sports drinks are loaded with sugar, artificial dyes, and ingredients designed for adult athletes. HydroWild was specifically formulated for kids' smaller bodies and developing systems — zero sugar, no artificial anything, and vitamins that actually support growth and immunity, not just electrolyte replacement."],
    ['How often should my child drink HydroWild?', "It's designed for daily use. The vitamins are dosed at levels appropriate for kids, not megadoses. Think of it like a daily hydration habit with built-in nutritional support."],
    ['Where are your products manufactured?', "HydroWild is proudly made in the USA. Our products are also third-party tested, so you can trust what's on the label is exactly what's inside."],
    ['Where does the color come from?', "No artificial dyes here. The colors in our flavors come from fruit and vegetable juice powder. It's the same ingredient used in many clean-label kids' products and completely safe for everyday use."],
    ["What's actually in it? (The real ingredient list)", `Each stick contains: citric acid, ${flavorLine}, ${colorSource}, and stevia extract (Reb A). Plus 7 vitamins (A, C, D, K, B6, B9/folate, B12) and 2 electrolytes — magnesium and potassium. That's it. Nothing you can't pronounce.`],
  ];

  const pdpFaqAcc = document.getElementById('pdpFaqAcc');
  if (pdpFaqAcc) {
    pdpFaqAcc.innerHTML = FAQS.map(
      ([q, a]) => `
      <div class="pdp__acc-item">
        <button class="pdp__acc-head">${q} <span>+</span></button>
        <div class="pdp__acc-body"><div class="pdp__acc-body-inner">${a}</div></div>
      </div>`
    ).join('');
  }

  // ── Accordion (runs AFTER dynamic sections are injected) ──
  document.querySelectorAll('.pdp__acc-item').forEach((item) => {
    const head = item.querySelector('.pdp__acc-head');
    const body = item.querySelector('.pdp__acc-body');
    const sync = () => { body.style.maxHeight = item.classList.contains('open') ? `${body.scrollHeight}px` : '0px'; };
    head.addEventListener('click', () => { item.classList.toggle('open'); sync(); });
    // re-sync open panels once images load
    body.querySelectorAll('img').forEach((img) => img.addEventListener('load', sync));
    sync();
  });

  // ── Other flavors grid ──
  const moreGrid = document.getElementById('moreGrid');
  if (moreGrid) {
    moreGrid.innerHTML = FLAVORS.filter((f) => f.id !== product.id)
      .map(
        (f) => `
      <a class="flavor-card" href="/products/${f.id}/" style="--card-color:${f.color}">
        <img class="creature" src="${f.creatureImg}" alt="" loading="lazy" />
        <img class="pack" src="${f.packImg}" alt="HydroWild ${f.name}" loading="lazy" />
        <h3 style="color:${f.color}">${f.name}</h3>
        <p>${f.tagline}</p>
        <span class="btn btn--ghost" style="font-size:0.85rem;padding:0.6rem 1.4rem;">View</span>
      </a>`
      )
      .join('');
  }

  // ── Entrance animations ──
  gsap.from('.pdp__gallery', { opacity: 0, x: -40, duration: 0.9, ease: 'power3.out', clearProps: 'transform,opacity' });
  gsap.from('.pdp__info > *', { opacity: 0, y: 28, stagger: 0.08, duration: 0.75, ease: 'power3.out', delay: 0.15, clearProps: 'transform,opacity' });
  gsap.to('#creatureBg', { yPercent: -6, xPercent: 4, duration: 5, yoyo: true, repeat: -1, ease: 'sine.inOut' });

  // ── Wild Difference + testimonial entrances ──
  gsap.from('.pdp-diff__inner > *', {
    opacity: 0, y: 34, stagger: 0.12, duration: 0.8,
    ease: 'power3.out', clearProps: 'transform,opacity',
    scrollTrigger: { trigger: '.pdp-diff', start: 'top 78%', once: true },
  });
  gsap.from('.pdp-quote__inner > *', {
    opacity: 0, y: 34, stagger: 0.12, duration: 0.8,
    ease: 'power3.out', clearProps: 'transform,opacity',
    scrollTrigger: { trigger: '.pdp-quote', start: 'top 78%', once: true },
  });

  // ── Why-cards stagger ──
  gsap.from('.pdp-why__card', {
    opacity: 0, y: 32, stagger: 0.1, duration: 0.7,
    ease: 'power3.out', clearProps: 'transform,opacity',
    scrollTrigger: { trigger: '#whyGrid', start: 'top 84%', once: true },
  });

  // ── Other flavors cards stagger ──
  gsap.from('.flavor-card', {
    opacity: 0, y: 40, scale: 0.94, stagger: 0.12, duration: 0.75,
    ease: 'back.out(1.4)', clearProps: 'transform,opacity',
    scrollTrigger: { trigger: '#moreGrid', start: 'top 82%', once: true },
  });

  // ── Footer stagger ──
  gsap.from('.footer__brand, .footer__cols > div', {
    opacity: 0, y: 30, stagger: 0.1, duration: 0.7, ease: 'power3.out',
    clearProps: 'transform,opacity',
    scrollTrigger: { trigger: '.footer', start: 'top 88%', once: true },
  });
}
